name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: gradle assembleDebug --no-daemon --stacktrace
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WorkLog-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7

       - name: Create debug keystore
        run: |
          keytool -genkey -v \
            -keystore debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"
